#!/usr/bin/env python3
from bs4 import BeautifulSoup, NavigableString, Tag
from docx import Document
from docx.shared import Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.oxml.ns import qn
import subprocess, pathlib, re, sys

CHAPTERS = [
(1,"work/chapter-01-u-2026-09-28","working/chapter-01_U_2026-09-28.html"),
(2,"work/chapter-02-u-2026-09-28","working/chapter-02_U_2026-09-28.html"),
(3,"work/chapter-03-u-2026-09-28","working/chapter-03_U_2026-09-28.html"),
(4,"work/chapter-04-u-2026-09-28","working/chapter-04_U_2026-09-28.html"),
(5,"work/chapter-05-u-2026-09-28","working/chapter-05_U_2026-09-28.html"),
(6,"work/chapter-06-u-2026-09-28","working/chapter-06_U_2026-09-28.html"),
(7,"work/chapter-07-u-2026-09-28","working/chapter-07_U_2026-09-28.html"),
(8,"work/chapter-08-u-2026-09-28","working/chapter-08_U_2026-09-28.html"),
(9,"work/chapter-09-u-2026-09-28","working/chapter-09_U_2026-09-28.html"),
(10,"work/chapter-10-u-2026-09-28","working/chapter-10_U_2026-09-28.html"),
(11,"work/chapter-11-u-2026-09-28","working/chapter-11_U_2026-09-28.html"),
]

def git_show(branch,path):
    cp=subprocess.run(["git","show",f"origin/{branch}:{path}"],check=True,capture_output=True)
    return cp.stdout.decode("utf-8")

def add_inline(par, node, bold=False, italic=False):
    if isinstance(node, NavigableString):
        if str(node):
            r=par.add_run(str(node)); r.bold=bold; r.italic=italic
        return
    if not isinstance(node, Tag): return
    name=node.name.lower()
    if name=="br":
        par.add_run().add_break(); return
    nb=bold or name in ("strong","b")
    ni=italic or name in ("em","i")
    for child in node.children:
        add_inline(par,child,nb,ni)

def norm(s):
    return re.sub(r"\s+"," ",s).strip()

doc=Document()
sec=doc.sections[0]
sec.top_margin=Cm(2); sec.bottom_margin=Cm(2); sec.left_margin=Cm(2.2); sec.right_margin=Cm(2.0)
style=doc.styles["Normal"]
style.font.name="Times New Roman"; style._element.rPr.rFonts.set(qn("w:eastAsia"),"Times New Roman"); style.font.size=Pt(12)
style.paragraph_format.space_after=Pt(3)
style.paragraph_format.line_spacing=1.08

expected=[]
chapter_counts=[]
for pos,(ch,branch,path) in enumerate(CHAPTERS):
    html=git_show(branch,path)
    soup=BeautifulSoup(html,"lxml")
    article=soup.find("article",class_="chapter-text")
    if article is None:
        raise RuntimeError(f"Chapter {ch}: article.chapter-text not found")
    blocks=article.find_all(["p","h1"],recursive=False)
    chapter_counts.append((ch,len(blocks)))
    if pos>0:
        doc.add_page_break()
    for el in blocks:
        txt=norm(el.get_text(" ",strip=True))
        expected.append(txt)
        if el.name=="h1":
            p=doc.add_paragraph()
            p.alignment=WD_ALIGN_PARAGRAPH.CENTER
            p.paragraph_format.space_before=Pt(0); p.paragraph_format.space_after=Pt(10)
            r=p.add_run(txt); r.bold=True; r.font.size=Pt(15)
        elif "part-label" in (el.get("class") or []):
            p=doc.add_paragraph()
            p.alignment=WD_ALIGN_PARAGRAPH.CENTER
            r=p.add_run(txt); r.bold=True
        elif "scene-break" in (el.get("class") or []):
            p=doc.add_paragraph()
            p.alignment=WD_ALIGN_PARAGRAPH.CENTER
            p.add_run(txt)
        else:
            p=doc.add_paragraph()
            for child in el.children:
                add_inline(p,child)
            p.paragraph_format.first_line_indent=Cm(0.65)

doc.core_properties.title="В зоне видимости"
doc.core_properties.author="Ирэн Кипо"
out=pathlib.Path("artifacts/В_зоне_видимости_Книга_1_FINAL_EDIT_2026-09-28.docx")
out.parent.mkdir(parents=True,exist_ok=True)
doc.save(out)

# Exact text QC: every source block must equal corresponding DOCX paragraph text
check=Document(out)
actual=[norm(p.text) for p in check.paragraphs]
# Page-break paragraphs generated by python-docx are blank; discard only blanks.
actual_nonblank=[x for x in actual if x!=""]
expected_nonblank=[x for x in expected if x!=""]
if actual_nonblank != expected_nonblank:
    for i,(a,b) in enumerate(zip(expected_nonblank,actual_nonblank)):
        if a!=b:
            print("FIRST_MISMATCH",i,repr(a),repr(b))
            break
    print("expected",len(expected_nonblank),"actual",len(actual_nonblank))
    sys.exit(2)
if len(CHAPTERS)!=11:
    sys.exit(3)
print("QC_PASS")
print("chapters",chapter_counts)
print("paragraphs",len(expected_nonblank))
print("output",out)
