from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
HTML='''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f2e8"><meta name="description" content="Ирэн Кипо. Серия романов «Всё хорошо»."><title>Ирэн Кипо — серия романов «Всё хорошо»</title><link rel="icon" href="assets/brand/ik-logo.jpg" type="image/jpeg"><link rel="stylesheet" href="assets/css/site.css"><link rel="stylesheet" href="assets/css/final.css"><script src="assets/js/site.js" defer></script></head><body>
<a class="skip-link" href="#content">К содержанию</a><header class="site-header" id="top"><a class="brand" href="#top" aria-label="Ирэн Кипо — на главную"><img src="assets/brand/ik-logo.jpg" alt="Авторский знак Ирэн Кипо" width="72" height="72"><span>Ирэн Кипо</span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Меню</button><nav class="nav" id="site-nav" aria-label="Основная навигация"><a href="#series">Серия</a><a href="#books">Книги</a><a href="#read">Читать</a><a href="#author">Автор</a><a href="#texts">Тексты</a><a href="#contacts">Контакты</a></nav></header>
<main id="content"><section class="hero hero-approved" aria-label="Серия романов «Всё хорошо»"><figure class="hero-art"><img src="assets/approved/series-banner.png" alt="Баннер серии романов «Всё хорошо»: центральная женщина и пять светлых семейных силуэтов со спины" width="2048" height="775"></figure></section>
<section class="section book-feature" id="books" aria-labelledby="book1-title"><figure class="book-mockup"><img src="assets/approved/book-1-3d.png" alt="Объёмная книга «В зоне видимости» с видимым корешком и страницами" width="1254" height="1254"></figure><div class="book-copy"><p class="eyebrow">КНИГА 1 СЕРИИ «ВСЁ ХОРОШО»</p><h2 id="book1-title">«В зоне видимости»</h2><div class="approved-description"><p>За жизнью Веры и Арсения Ланских следят миллионы. Семейный блог «Всё хорошо» вырос вместе с их семьёй: любовь, трое детей, работа, успех — и привычка делиться частью своей жизни с другими.</p><p>Когда новая технология обещает освободить их от постоянной съёмки, решение выглядит простым: теперь можно меньше думать о контенте и больше быть вместе.</p><p>Если всё хорошо — почему бы не сделать ещё лучше?</p></div><div class="actions" id="read"><a class="button primary" href="read/">Читать бесплатно</a><button class="button secondary" type="button" data-open="audio">Слушать бесплатно</button><button class="button secondary" type="button" data-open="download">Скачать</button></div></div></section>
'''
HTML+='''<section class="section series-section" id="series" aria-labelledby="series-title"><header class="section-heading"><p class="section-number">01</p><div><p class="eyebrow">ВСЯ СЕРИЯ</p><h2 id="series-title">Четыре книги</h2><p>4 книги. Одна история. Разные грани.</p></div></header><div class="series-grid">
<article class="series-card current"><img src="assets/approved/book-1-cover.png" alt="Обложка книги 1 «В зоне видимости»" width="1024" height="1536"><p class="book-number">Книга 1</p><h3>«В зоне видимости»</h3><p>опубликована</p></article>
<article class="series-card"><img src="assets/approved/book-2-cover.png" alt="Обложка книги 2 «Правила игры»" width="1024" height="1536"><p class="book-number">Книга 2</p><h3>«Правила игры»</h3><p>в работе</p></article>
<article class="series-card"><img src="assets/approved/book-3-cover.png" alt="Обложка книги 3 «Другая Вера»" width="1024" height="1536"><p class="book-number">Книга 3</p><h3>«Другая Вера»</h3><p>продолжение серии</p></article>
<article class="series-card"><img src="assets/approved/book-4-cover.png" alt="Обложка книги 4 «Ничего личного»" width="1024" height="1536"><p class="book-number">Книга 4</p><h3>«Ничего личного»</h3><p>финальная книга</p></article></div></section>
<section class="section next-book" id="texts" aria-labelledby="next-title"><figure class="book-mockup"><img src="assets/approved/book-2-3d.png" alt="Объёмная книга «Правила игры» с видимым корешком и страницами" width="1254" height="1254"></figure><div><p class="eyebrow">КНИГА 2</p><h2 id="next-title">БУДЬТЕ В КУРСЕ</h2><p>Подпишитесь, чтобы узнать о выходе новой книги и получать новости серии «Всё хорошо».</p><form class="subscription-form" data-subscription-form novalidate><label class="sr-only" for="subscription-email">Электронная почта</label><div class="subscription-row"><input id="subscription-email" name="email" type="email" inputmode="email" autocomplete="email" required placeholder="Ваш e-mail" aria-describedby="subscription-status"><button type="submit">Подписаться</button></div><p class="subscription-status" id="subscription-status" data-subscription-status role="status" aria-live="polite"></p></form></div></section>
<section class="section author-section" id="author" aria-labelledby="author-title"><figure class="author-mark"><img src="assets/brand/ik-logo.jpg" alt="Авторский знак Ирэн Кипо" width="800" height="800"></figure><div><p class="eyebrow">АВТОР</p><h2 id="author-title">Ирэн Кипо</h2><p>Писатель. Истории о людях, которые ищут, любят и остаются собой. Страницы разные. Всё хорошо.</p></div><a class="button primary" href="#texts">Подписаться на новости</a></section>
'''
HTML+='''<section class="section social-section" id="contacts" aria-labelledby="social-title"><p class="eyebrow">СОЦИАЛЬНЫЕ СЕТИ</p><h2 id="social-title">Ирэн Кипо</h2><nav class="social-links" aria-label="Социальные сети"><a href="https://www.instagram.com/irenkipo/" target="_blank" rel="noopener">Instagram</a><a href="https://www.facebook.com/1236694432869766" target="_blank" rel="noopener">Facebook</a><a href="https://www.threads.com/@irenkipo" target="_blank" rel="noopener">Threads</a></nav></section>
<section class="section litres-section" aria-labelledby="litres-title"><div><p class="eyebrow">ЛИТРЕС</p><h2 id="litres-title">«В зоне видимости»</h2></div><a class="button primary" href="https://www.litres.ru/74382683/" target="_blank" rel="noopener">Читать на ЛитРес</a></section></main>
<footer class="footer"><a class="footer-brand" href="#top"><img src="assets/brand/ik-logo.jpg" alt="" width="52" height="52"><span>Ирэн Кипо</span></a><p>© 2026 Ирэн Кипо. Все права защищены.</p><nav aria-label="Правовая информация"><a href="privacy.html">Конфиденциальность</a><a href="terms.html">Условия</a></nav></footer>
<div class="modal" id="download" role="dialog" aria-modal="true" aria-labelledby="download-title" hidden><div class="modal-card"><header class="modal-head"><h2 id="download-title">Скачать «В зоне видимости»</h2><button type="button" data-close aria-label="Закрыть">×</button></header><div class="download-list"><a href="assets/books/book1.epub" download><strong>EPUB</strong><span>Скачать</span></a><a href="assets/books/book1.pdf" download><strong>PDF</strong><span>Скачать</span></a><button type="button" data-audio-download disabled><strong>MP3 · аудио</strong><span>файл готовится</span></button></div></div></div>
<div class="modal" id="audio" role="dialog" aria-modal="true" aria-labelledby="audio-title" hidden><div class="modal-card audio-card"><header class="modal-head"><div><p class="eyebrow">АУДИОКНИГА</p><h2 id="audio-title">«В зоне видимости»</h2></div><button type="button" data-close aria-label="Закрыть">×</button></header><div class="audio-placeholder" data-audio-slot data-audio-mode="placeholder"><p class="audio-placeholder-badge">Скоро</p><p class="audio-placeholder-title" data-audio-status aria-live="polite">Многоголосая аудиокнига готовится</p></div></div></div></body></html>'''
LEGAL='''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — Ирэн Кипо</title><link rel="stylesheet" href="assets/css/site.css"></head><body><main class="section"><p class="kicker">ИРЭН КИПО</p><h1>{title}</h1><p>{text}</p><p><a class="button primary" href="./">На главную</a></p></main></body></html>'''
def write(rel,text):
    path=ROOT/rel
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(text,encoding="utf-8")
write("index.html",HTML)
write("privacy.html",LEGAL.format(title="Конфиденциальность",text="Сайт не принимает платежи. Данные подписки будут обрабатываться сервисом рассылки после подключения формы и только с согласия подписчика."))
write("terms.html",LEGAL.format(title="Условия использования",text="Тексты и визуальные материалы сайта защищены авторским правом. Бесплатные файлы предназначены для личного чтения и прослушивания."))
write("404.html",LEGAL.format(title="Страница не найдена",text="Запрошенной страницы нет."))
write("robots.txt","User-agent: *\nAllow: /\nSitemap: https://irenkipo.github.io/sitemap.xml\n")
write("sitemap.xml",'''<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://irenkipo.github.io/</loc></url><url><loc>https://irenkipo.github.io/read/</loc></url><url><loc>https://irenkipo.github.io/privacy.html</loc></url><url><loc>https://irenkipo.github.io/terms.html</loc></url></urlset>''')
